# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  dmcnews:
    image: dmcnews
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      INIT_TAGS_FILE: /data/tags.csv
      ConnectionStrings__DefaultConnection: "Host=db;Database=dmcnews;Username=dmcnews;Password=hala29an3"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./Data:/data
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dmcnews
      POSTGRES_PASSWORD: hala29an3
      POSTGRES_DB: dmcnews
