name: Build

on:
  push:
    branch:
      - master
jobs:
  build-publish:
    name: Build
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $DOCKER_REPOSITORY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/} ./dmc-social
