name: Release

on:
  release:
    types:
      - published
jobs:
  build-publish:
    env:
      DOCKER_REPOSITORY: docker.pkg.github.com
      IMAGE: dmcnews
    name: Build and push
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $DOCKER_REPOSITORY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/} ./dmc-social
      - name: Login docker repository
        run: docker login $DOCKER_REPOSITORY -u $GITHUB_ACTOR --password ${{secrets.GITHUB_TOKEN}}
      - name: Publish
        run: docker push $DOCKER_REPOSITORY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/}
