name: Release

on:
  release:
    types:
      - published
jobs:
  build-publish:
    env:
      DOCKER_REPOSITORY: docker.pkg.github.com
      IMAGE: social
      JOB_IMAGE: social-job
    name: Build and push
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Login docker repository
        run: echo ${{ secrets.CR_PAT }} | docker login $DOCKER_REPOSITORY -u $GITHUB_ACTOR --password-stdin
      - uses: FranzDiebold/github-env-vars-action@v2
      # Build the Docker image
      - run: |
          docker build -t $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:$CI_ACTION_REF_NAME .
          docker push $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:$CI_ACTION_REF_NAME
          docker build -t $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$JOB_IMAGE:$CI_ACTION_REF_NAME . -f worker.Dockerfile
          docker push $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$JOB_IMAGE:$CI_ACTION_REF_NAME
